name:   Student Management Pipline/workflow

on: 
   push:
    Branches:["main"]

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
       - name: checkout repository
         uses: actions/checkout@v3

      - name: Set up python
        uses: action/setup-python@v3
        with: 
          python-version: "3.10"

      - name: install Dependencis
      run: pip install -r requirements


          
     
